### ISSUE TITLE
Add a 3 retries

### ISSUE THREAD

**Issue by gianmarcogg03** [Duncaen/OpenDoas#98] opened 2022-04-17 20:38 UTC
When you type the password wrong it fails to execute the command, while sudo asks you for the password two more times instead. Can you add this feature?

**Comment by Duncaen** [comment] 2022-04-19 02:04
Will be in the next release, duplicate of https://github.com/Duncaen/OpenDoas/issues/82.

**Closed as completed by Duncaen** 2022-04-19 02:04 UTC
