### ISSUE TITLE
please support systemd-homed

### ISSUE THREAD

**Issue by basedtho** [Duncaen/OpenDoas#31] opened 2020-06-11 21:20 UTC
sudo already does that

**Comment by Duncaen** [comment] 2020-06-11 22:00
This should work with pam.

**Comment by Duncaen** [comment] 2020-06-11 22:02
That said, I don't use systemd and I don't think I would personally want to add extra code for system.
It _should_ work by default and sudo does nothing special either.

**Comment by basedtho** [comment] 2020-06-11 22:24
do i need to add something to doas.conf? because right now it doesn't work

>doas (tho@unix) password: 
>doas: Authorization failed

**Comment by Duncaen** [comment] 2020-06-11 22:27
Nothing except the rule to allow the username to use doas (not the uid, because with homed I assume it is not stable).
Just make sure its using pam, maybe compare the sudo and doas pam configuration in `/etc/pam.d` to see if your distribution enabled anything special in it to support systemd-home.d

**Comment by basedtho** [comment] 2020-06-11 22:32
my doas.conf is as follows

```
permit persist tho
```
/etc/pam.d/doas
```
#%PAM-1.0
auth            required        pam_unix.so
account         required        pam_unix.so
session         optional        pam_xauth.so
session         optional        pam_umask.so     usergroups umask=022
session         required        pam_env.so
session         required        pam_unix.so
```

/etc/pam.d/sudo
```
#%PAM-1.0
auth            include         system-auth
account         include         system-auth
session         include         system-auth
```
#%PAM-1.0
auth            include         system-auth
account         include         system-auth
session         include         system-auth

i don't understand how pam works at all, so i'm asking for your help. thank you for your time

**Comment by Duncaen** [comment] 2020-06-11 22:35
Maybe try something like the following for `/etc/pam.d/doas`:

```
#%PAM-1.0
auth            include         system-auth
account         include         system-auth
session         include         system-auth
session         optional        pam_umask.so     usergroups umask=022
```

This is the only difference I could think of, that the system-auth and other included pam configuration files hook in some systemd pam module to support systemd-homed.

**Comment by basedtho** [comment] 2020-06-11 22:40
it says 
>doas: pam_close_session: Cannot make/remove an entry for the specified session
after a doas command

and here's an excerpt from dmesg

```
[ 2544.141020] audit: type=1101 audit(1591915068.437:220): pid=6128 uid=60047 auid=60047 ses=2 msg='op=PAM:accounting grantors=pam_systemd_home,pam_permit,pam_time acct="tho" exe="/usr/bin/doas" hostname=unix addr=? terminal=pts/0 res=success'
[ 2544.141416] audit: type=1103 audit(1591915068.437:221): pid=6128 uid=60047 auid=60047 ses=2 msg='op=PAM:setcred grantors=pam_systemd_home,pam_permit acct="root" exe="/usr/bin/doas" hostname=unix addr=? terminal=pts/0 res=success'
[ 2544.141640] audit: type=1105 audit(1591915068.437:222): pid=6128 uid=60047 auid=60047 ses=2 msg='op=PAM:session_open grantors=pam_limits,pam_systemd_home,pam_unix,pam_permit,pam_umask acct="root" exe="/usr/bin/doas" hostname=unix addr=? terminal=pts/0 res=success'
[ 2545.789696] audit: type=1106 audit(1591915070.087:223): pid=6128 uid=60047 auid=60047 ses=2 msg='op=PAM:session_close grantors=? acct="root" exe="/usr/bin/doas" hostname=unix addr=? terminal=pts/0 res=failed'
```

**Comment by Duncaen** [comment] 2020-06-11 23:30
Thanks for the logs I will look into this further.

**Comment by Duncaen** [comment] 2020-11-14 14:36
I'm unable to reproduce the issue, is this still happening for you @basedtho?

**Comment by basedtho** [comment] 2020-11-14 14:43
unfortunately, i've stopped using doas, because it does not have a feature i need (`Defaults rootpw`)

**Comment by Duncaen** [comment] 2020-11-14 14:48
Ok then I'm closing this for now, if someone else runs into the issue please open a new one with more details.

**Closed by Duncaen** 2020-11-14 14:48 UTC
